  export const siteConfig = {
    name: "ShockFit Epil",
    description: "",
    navItems: [
      { label: "Početna",
        href: "/",
          sectionId: "home" },
      { label: "O nama",
        href: "/about-us", 
        sectionId: "nama" },
      { label: "Usluge",
        href: "/services",
          sectionId: "usluge" },
      { label: "Zašto odabrati nas",
        href: "/why-choose-us",
          sectionId: "choose" },
      { label: "Blog",
        href: "/blog" },
      { label: "Gallery",
        href: "/gallery" },
    ],
    navMenuItems: [
      { label: "Početna", href: "/", sectionId: "home" },
      { label: "O nama", href: "/about-us", sectionId: "nama" },
      { label: "Usluge", href: "/#", sectionId: "usluge" },
      { label: "Zašto odabrati nas", href: "/why-choose-us", sectionId: "choose" },
    ],
    links: {
      github: "https://github.com",
      twitter: "https://twitter.com",
      docs: "#form",
      discord: "#form",
      sponsor: "#form",
    },
  };
